import { DropDownList } from '../../models/application-form-interface'

export const birthPlaceList: DropDownList[] = [
    { value: "AFGH", name: 'AFGHANISTAN' },
    { value: "ALB", name: 'ALBANIA' },
    { value: "ALGR", name: 'ALGERIA' },
    { value: "ASMO", name: 'AMERICAN SAMOA' },
    { value: "ANDO", name: 'ANDORRA' },
    { value: "ANGL", name: 'ANGOLA' },
    { value: "ANGU", name: 'ANGUILLA' },
    { value: "ANTI", name: 'ANTIGUA AND BARBUDA' },
    { value: "ARG", name: 'ARGENTINA' },
    { value: "ARM", name: 'ARMENIA' },
    { value: "ARB", name: 'ARUBA' },
    { value: "XAS", name: 'AT SEA' },
    { value: "ASTL", name: 'AUSTRALIA' },
    { value: "AUST", name: 'AUSTRIA' },
    { value: "AZR", name: 'AZERBAIJAN' },
    { value: "BAMA", name: 'BAHAMAS' },
    { value: "BAHR", name: 'BAHRAIN' },
    { value: "BANG", name: 'BANGLADESH' },
    { value: "BRDO", name: 'BARBADOS' },
    { value: "BYS", name: 'BELARUS' },
    { value: "BELG", name: 'BELGIUM' },
    { value: "BLZ", name: 'BELIZE' },
    { value: "BENN", name: 'BENIN' },
    { value: "BERM", name: 'BERMUDA' },
    { value: "BHU", name: 'BHUTAN' },
    { value: "BOL", name: 'BOLIVIA' },
    { value: "BON", name: 'BONAIRE' },
    { value: "BIH", name: 'BOSNIA-HERZEGOVINA' },
    { value: "BOT", name: 'BOTSWANA' },
    { value: "BRZL", name: 'BRAZIL' },
    { value: "IOT", name: 'BRITISH INDIAN OCEAN TERRITORY' },
    { value: "BRNI", name: 'BRUNEI' },
    { value: "BULG", name: 'BULGARIA' },
    { value: "BURK", name: 'BURKINA FASO' },
    { value: "BURM", name: 'BURMA' },
    { value: "BRND", name: 'BURUNDI' },
    { value: "CBDA", name: 'CAMBODIA' },
    { value: "CMRN", name: 'CAMEROON' },
    { value: "CAN", name: 'CANADA' },
    { value: "CAVI", name: 'CABO VERDE' },
    { value: "CAYI", name: 'CAYMAN ISLANDS' },
    { value: "CAFR", name: 'CENTRAL AFRICAN REPUBLIC' },
    { value: "CHAD", name: 'CHAD' },
    { value: "CHIL", name: 'CHILE' },
    { value: "CHIN", name: 'CHINA' },
    { value: "CHRI", name: 'CHRISTMAS ISLAND' },
    { value: "COCI", name: 'COCOS KEELING ISLANDS' },
    { value: "COL", name: 'COLOMBIA' },
    { value: "COMO", name: 'COMOROS' },
    { value: "COD", name: 'CONGO, DEMOCRATIC REPUBLIC OF THE' },
    { value: "CONB", name: 'CONGO, REPUBLIC OF THE' },
    { value: "CKIS", name: 'COOK ISLANDS' },
    { value: "CSTR", name: 'COSTA RICA' },
    { value: "IVCO", name: 'COTE D`IVOIRE' },
    { value: "HRV", name: 'CROATIA' },
    { value: "CUBA", name: 'CUBA' },
    { value: "CUR", name: 'CURACAO' },
    { value: "CYPR", name: 'CYPRUS' },
    { value: "CZEC", name: 'CZECH REPUBLIC' },
    { value: "DEN", name: 'DENMARK' },
    { value: "DJI", name: 'DJIBOUTI' },
    { value: "DOMN", name: 'DOMINICA' },
    { value: "DOMR", name: 'DOMINICAN REPUBLIC' },
    { value: "ECUA", name: 'ECUADOR' },
    { value: "EGYP", name: 'EGYPT' },
    { value: "ELSL", name: 'EL SALVADOR' },
    { value: "EGN", name: 'EQUATORIAL GUINEA' },
    { value: "ERI", name: 'ERITREA' },
    { value: "EST", name: 'ESTONIA' },
    { value: "SZLD", name: 'ESWATINI' },
    { value: "ETH", name: 'ETHIOPIA' },
    { value: "FKLI", name: 'FALKLAND ISLANDS' },
    { value: "FRO", name: 'FAROE ISLANDS' },
    { value: "FIJI", name: 'FIJI' },
    { value: "FIN", name: 'FINLAND' },
    { value: "FRAN", name: 'FRANCE' },
    { value: "FRGN", name: 'FRENCH GUIANA' },
    { value: "FPOL", name: 'FRENCH POLYNESIA' },
    { value: "FSAT", name: 'FRENCH SOUTHERN AND ANTARCTIC TERRITORIES' },
    { value: "GABN", name: 'GABON' },
    { value: "GAM", name: 'GAMBIA, THE' },
    { value: "XGZ", name: 'GAZA STRIP' },
    { value: "GEO", name: 'GEORGIA' },
    { value: "GER", name: 'GERMANY' },
    { value: "GHAN", name: 'GHANA' },
    { value: "GIB", name: 'GIBRALTAR' },
    { value: "GRC", name: 'GREECE' },
    { value: "GRLD", name: 'GREENLAND' },
    { value: "GREN", name: 'GRENADA' },
    { value: "GUAD", name: 'GUADELOUPE' },
    { value: "GUAM", name: 'GUAM' },
    { value: "GUAT", name: 'GUATEMALA' },
    { value: "GNEA", name: 'GUINEA' },
    { value: "GUIB", name: 'GUINEA - BISSAU' },
    { value: "GUY", name: 'GUYANA' },
    { value: "HAT", name: 'HAITI' },
    { value: "HMD", name: 'HEARD AND MCDONALD ISLANDS' },
    { value: "VAT", name: 'HOLY SEE (VATICAN CITY)' },
    { value: "HOND", name: 'HONDURAS' },
    { value: "HOKO", name: 'HONG KONG BNO' },
    { value: "HNK", name: 'HONG KONG SAR' },
    { value: "XHI", name: 'HOWLAND ISLAND' },
    { value: "HUNG", name: 'HUNGARY' },
    { value: "ICLD", name: 'ICELAND' },
    { value: "XIR", name: 'IN THE AIR' },
    { value: "IND", name: 'INDIA' },
    { value: "IDSA", name: 'INDONESIA' },
    { value: "IRAN", name: 'IRAN' },
    { value: "IRAQ", name: 'IRAQ' },
    { value: "IRE", name: 'IRELAND' },
    { value: "ISRL", name: 'ISRAEL' },
    { value: "ITLY", name: 'ITALY' },
    { value: "JAM", name: 'JAMAICA' },
    { value: "JPN", name: 'JAPAN' },
    { value: "JRSM", name: 'JERUSALEM' },
    { value: "JORD", name: 'JORDAN' },
    { value: "KAZ", name: 'KAZAKHSTAN' },
    { value: "KENY", name: 'KENYA' },
    { value: "KIRI", name: 'KIRIBATI' },
    { value: "PRK", name: 'KOREA, DEMOCRATIC REPUBLIC OF (NORTH)' },
    { value: "KOR", name: 'KOREA, REPUBLIC OF (SOUTH)' },
    { value: "KSV", name: 'KOSOVO' },
    { value: "KUWT", name: 'KUWAIT' },
    { value: "KGZ", name: 'KYRGYZSTAN' },
    { value: "LAOS", name: 'LAOS' },
    { value: "LATV", name: 'LATVIA' },
    { value: "LEBN", name: 'LEBANON' },
    { value: "LES", name: 'LESOTHO' },
    { value: "LIBR", name: 'LIBERIA' },
    { value: "LBYA", name: 'LIBYA' },
    { value: "LCHT", name: 'LIECHTENSTEIN' },
    { value: "LITH", name: 'LITHUANIA' },
    { value: "LXM", name: 'LUXEMBOURG' },
    { value: "MAC", name: 'MACAU' },
    { value: "MKD", name: 'MACEDONIA, NORTH' },
    { value: "MADG", name: 'MADAGASCAR' },
    { value: "MALW", name: 'MALAWI' },
    { value: "MLAS", name: 'MALAYSIA' },
    { value: "MLDI", name: 'MALDEN ISLAND' },
    { value: "MLDV", name: 'MALDIVES' },
    { value: "MALI", name: 'MALI' },
    { value: "MLTA", name: 'MALTA' },
    { value: "RMI", name: 'MARSHALL ISLANDS' },
    { value: "MART", name: 'MARTINIQUE' },
    { value: "MAUR", name: 'MAURITANIA' },
    { value: "MRTS", name: 'MAURITIUS' },
    { value: "MYT", name: 'MAYOTTE' },
    { value: "AGS", name: 'MEXICO - AGUASCALIENTES' },
    { value: "BC", name: 'MEXICO - BAJA CALIFORNIA NORTE' },
    { value: "BCSR", name: 'MEXICO - BAJA CALIFORNIA SUR' },
    { value: "CAMP", name: 'MEXICO - CAMPECHE' },
    { value: "CHIS", name: 'MEXICO - CHIAPAS' },
    { value: "CHIH", name: 'MEXICO - CHIHUAHUA' },
    { value: "COAH", name: 'MEXICO - COAHUILA' },
    { value: "COLI", name: 'MEXICO - COLIMA' },
    { value: "DF", name: 'MEXICO - DISTRITO FEDERAL' },
    { value: "DGO", name: 'MEXICO - DURANGO' },
    { value: "GTO", name: 'MEXICO - GUANAJUATO' },
    { value: "GRO", name: 'MEXICO - GUERRERO' },
    { value: "HGO", name: 'MEXICO - HIDALGO' },
    { value: "JAL", name: 'MEXICO - JALISCO' },
    { value: "MCH", name: 'MEXICO - MICHOACAN' },
    { value: "MOR", name: 'MEXICO - MORELOS' },
    { value: "NAY", name: 'MEXICO - NAYARIT' },
    { value: "NL", name: 'MEXICO - NUEVO LEON' },
    { value: "OAX", name: 'MEXICO - OAXACA' },
    { value: "PUE", name: 'MEXICO - PUEBLA' },
    { value: "QRO", name: 'MEXICO - QUERETARO' },
    { value: "QROO", name: 'MEXICO - QUINTANA ROO' },
    { value: "SLP", name: 'MEXICO - SAN LUIS POTOSI' },
    { value: "SIN", name: 'MEXICO - SINALOA' },
    { value: "SON", name: 'MEXICO - SONORA' },
    { value: "MXCO", name: 'MEXICO - STATE OF MEXICO' },
    { value: "TAB", name: 'MEXICO - TABASCO' },
    { value: "TAMP", name: 'MEXICO - TAMAULIPAS' },
    { value: "TLAX", name: 'MEXICO - TLAXCALA' },
    { value: "VER", name: 'MEXICO - VERACRUZ' },
    { value: "YUC", name: 'MEXICO - YUCATAN' },
    { value: "ZAC", name: 'MEXICO - ZACATECAS' },
    { value: "FSM", name: 'MICRONESIA' },
    { value: "MDWI", name: 'MIDWAY ISLANDS' },
    { value: "MLD", name: 'MOLDOVA' },
    { value: "MON", name: 'MONACO' },
    { value: "MONG", name: 'MONGOLIA' },
    { value: "MTG", name: 'MONTENEGRO' },
    { value: "MONT", name: 'MONTSERRAT' },
    { value: "MORO", name: 'MOROCCO' },
    { value: "MOZ", name: 'MOZAMBIQUE' },
    { value: "NAMB", name: 'NAMIBIA' },
    { value: "NAU", name: 'NAURU' },
    { value: "NEP", name: 'NEPAL' },
    { value: "NETH", name: 'NETHERLANDS' },
    { value: "NCAL", name: 'NEW CALEDONIA' },
    { value: "NZLD", name: 'NEW ZEALAND' },
    { value: "NIC", name: 'NICARAGUA' },
    { value: "NIR", name: 'NIGER' },
    { value: "NRA", name: 'NIGERIA' },
    { value: "NIUE", name: 'NIUE' },
    { value: "NFK", name: 'NORFOLK ISLAND' },
    { value: "MNP", name: 'NORTH MARIANA ISLANDS' },
    { value: "NIRE", name: 'NORTHERN IRELAND' },
    { value: "NORW", name: 'NORWAY' },
    { value: "OMAN", name: 'OMAN' },
    { value: "PKST", name: 'PAKISTAN' },
    { value: "PALA", name: 'PALAU' },
    { value: "PLMR", name: 'PALMYRA ATOLL' },
    { value: "PAN", name: 'PANAMA' },
    { value: "PNG", name: 'PAPUA NEW GUINEA' },
    { value: "PARA", name: 'PARAGUAY' },
    { value: "PERU", name: 'PERU' },
    { value: "PHIL", name: 'PHILIPPINES' },
    { value: "PITC", name: 'PITCAIRN ISLANDS' },
    { value: "POL", name: 'POLAND' },
    { value: "PORT", name: 'PORTUGAL' },
    { value: "PR", name: 'PUERTO RICO' },
    { value: "QTAR", name: 'QATAR' },
    { value: "REUN", name: 'REUNION' },
    { value: "ROM", name: 'ROMANIA' },
    { value: "RUS", name: 'RUSSIA' },
    { value: "RWND", name: 'RWANDA' },
    { value: "SABA", name: 'SABA ISLAND' },
    { value: "MAF", name: 'SAINT MARTIN' },
    { value: "WSAM", name: 'SAMOA' },
    { value: "SMAR", name: 'SAN MARINO' },
    { value: "STPR", name: 'SAO TOME AND PRINCIPE' },
    { value: "SARB", name: 'SAUDI ARABIA' },
    { value: "SENG", name: 'SENEGAL' },
    { value: "SBA", name: 'SERBIA' },
    { value: "SEYC", name: 'SEYCHELLES' },
    { value: "SLEO", name: 'SIERRA LEONE' },
    { value: "SING", name: 'SINGAPORE' },
    { value: "STM", name: 'SINT MAARTEN' },
    { value: "SVK", name: 'SLOVAKIA' },
    { value: "SVN", name: 'SLOVENIA' },
    { value: "SLMN", name: 'SOLOMON ISLANDS' },
    { value: "SOMA", name: 'SOMALIA' },
    { value: "SAFR", name: 'SOUTH AFRICA' },
    { value: "SGS", name: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLAND' },
    { value: "SSDN", name: 'SOUTH SUDAN' },
    { value: "SPN", name: 'SPAIN' },
    { value: "SRL", name: 'SRI LANKA' },
    { value: "STBR", name: 'ST. BARTHELEMY' },
    { value: "STEU", name: 'ST. EUSTATIUS' },
    { value: "SHEL", name: 'ST. HELENA' },
    { value: "STCN", name: 'ST. KITTS AND NEVIS' },
    { value: "SLCA", name: 'ST. LUCIA' },
    { value: "SPMI", name: 'ST. PIERRE AND MIQUELON' },
    { value: "STVN", name: 'ST. VINCENT AND THE GRENADINES' },
    { value: "SUDA", name: 'SUDAN' },
    { value: "SURM", name: 'SURINAME' },
    { value: "SJM", name: 'SVALBARD' },
    { value: "SWDN", name: 'SWEDEN' },
    { value: "SWTZ", name: 'SWITZERLAND' },
    { value: "SYR", name: 'SYRIA' },
    { value: "TWAN", name: 'TAIWAN' },
    { value: "TJK", name: 'TAJIKISTAN' },
    { value: "TAZN", name: 'TANZANIA' },
    { value: "THAI", name: 'THAILAND' },
    { value: "TMOR", name: 'TIMOR-LESTE' },
    { value: "TOGO", name: 'TOGO' },
    { value: "TKL", name: 'TOKELAU' },
    { value: "TONG", name: 'TONGA' },
    { value: "TRIN", name: 'TRINIDAD AND TOBAGO' },
    { value: "TNSA", name: 'TUNISIA' },
    { value: "TRKY", name: 'TURKEY' },
    { value: "TKM", name: 'TURKMENISTAN' },
    { value: "TCIS", name: 'TURKS AND CAICOS ISLANDS' },
    { value: "TUV", name: 'TUVALU' },
    { value: "UGAN", name: 'UGANDA' },
    { value: "UKR", name: 'UKRAINE' },
    { value: "UAE", name: 'UNITED ARAB EMIRATES' },
    { value: "GRBR", name: 'UNITED KINGDOM' },
    { value: "USA", name: 'UNITED STATES OF AMERICA' },
    { value: "URU", name: 'URUGUAY' },
    { value: "UZB", name: 'UZBEKISTAN' },
    { value: "VANU", name: 'VANUATU' },
    { value: "VENZ", name: 'VENEZUELA' },
    { value: "VTNM", name: 'VIETNAM' },
    { value: "VI", name: 'VIRGIN ISLANDS (U.S.)' },
    { value: "BRVI", name: 'VIRGIN ISLANDS, BRITISH' },
    { value: "WKI", name: 'WAKE ISLAND' },
    { value: "WAFT", name: 'WALLIS AND FUTUNA ISLANDS' },
    { value: "XWB", name: 'WEST BANK' },
    { value: "SSAH", name: 'WESTERN SAHARA' },
    { value: "YEM", name: 'YEMEN' },
    { value: "ZAMB", name: 'ZAMBIA' },
    { value: "ZIMB", name: 'ZIMBABWE' },
]

export const applyLocationList: DropDownList[] = [
    { value: "KBL", name: "AFGHANISTAN, KABUL" },
    { value: "TIA", name: "ALBANIA, TIRANA" },
    { value: "ALG", name: "ALGERIA, ALGIERS" },
    { value: "LUA", name: "ANGOLA, LUANDA" },
    { value: "BNS", name: "ARGENTINA, BUENOS AIRES" },
    { value: "YRV", name: "ARMENIA, YEREVAN" },
    { value: "MLB", name: "AUSTRALIA, MELBOURNE" },
    { value: "PRT", name: "AUSTRALIA, PERTH" },
    { value: "SYD", name: "AUSTRALIA, SYDNEY" },
    { value: "VNN", name: "AUSTRIA, VIENNA" },
    { value: "BKU", name: "AZERBAIJAN, BAKU" },
    { value: "NSS", name: "BAHAMAS, NASSAU" },
    { value: "MNA", name: "BAHRAIN, MANAMA" },
    { value: "DHK", name: "BANGLADESH, DHAKA" },
    { value: "BGN", name: "BARBADOS, BRIDGETOWN" },
    { value: "MSK", name: "BELARUS, MINSK" },
    { value: "BRS", name: "BELGIUM, BRUSSELS" },
    { value: "BLZ", name: "BELIZE, BELMOPAN" },
    { value: "COT", name: "BENIN, COTONOU" },
    { value: "HML", name: "BERMUDA, HAMILTON" },
    { value: "LPZ", name: "BOLIVIA, LA PAZ" },
    { value: "SAR", name: "BOSNIA-HERZEGOVINA, SARAJEVO" },
    { value: "GAB", name: "BOTSWANA, GABORONE" },
    { value: "BRA", name: "BRAZIL, BRASILIA" },
    { value: "PTA", name: "BRAZIL, PORTO ALEGRE" },
    { value: "RCF", name: "BRAZIL, RECIFE" },
    { value: "RDJ", name: "BRAZIL, RIO DE JANEIRO" },
    { value: "SPL", name: "BRAZIL, SAO PAULO" },
    { value: "BSB", name: "BRUNEI, BANDAR SERI BEGAWAN" },
    { value: "SOF", name: "BULGARIA, SOFIA" },
    { value: "OUG", name: "BURKINA FASO, OUAGADOUGOU" },
    { value: "RNG", name: "BURMA, RANGOON" },
    { value: "BUJ", name: "BURUNDI, BUJUMBURA" },
    { value: "PIA", name: "CABO VERDE, PRAIA" },
    { value: "PHP", name: "CAMBODIA, PHNOM PENH" },
    { value: "YDE", name: "CAMEROON, YAOUNDE" },
    { value: "CLG", name: "CANADA, CALGARY" },
    { value: "HLF", name: "CANADA, HALIFAX" },
    { value: "MTL", name: "CANADA, MONTREAL" },
    { value: "OTT", name: "CANADA, OTTAWA" },
    { value: "QBC", name: "CANADA, QUEBEC" },
    { value: "TRT", name: "CANADA, TORONTO" },
    { value: "VAC", name: "CANADA, VANCOUVER" },
    { value: "NDJ", name: "CHAD, N`DJAMENA" },
    { value: "SNT", name: "CHILE, SANTIAGO" },
    { value: "BEJ", name: "CHINA, BEIJING" },
    { value: "CHE", name: "CHINA, CHENGDU" },
    { value: "GUZ", name: "CHINA, GUANGZHOU" },
    { value: "SHG", name: "CHINA, SHANGHAI" },
    { value: "SNY", name: "CHINA, SHENYANG" },
    { value: "BGT", name: "COLOMBIA, BOGOTA" },
    { value: "BRZ", name: "CONGO, BRAZZAVILLE" },
    { value: "KIN", name: "CONGO, KINSHASA" },
    { value: "SNJ", name: "COSTA RICA, SAN JOSE" },
    { value: "ABJ", name: "COTE D`IVORIE, ABIDJAN" },
    { value: "ZGB", name: "CROATIA, ZAGREB" },
    { value: "HAV", name: "CUBA, HAVANA" },
    { value: "CRC", name: "CURACAO, CURACAO" },
    { value: "NCS", name: "CYPRUS, NICOSIA" },
    { value: "PRG", name: "CZECH REPUBLIC, PRAGUE" },
    { value: "CPN", name: "DENMARK, COPENHAGEN" },
    { value: "DJI", name: "DJIBOUTI, DJIBOUTI" },
    { value: "SDO", name: "DOMINICAN REPUBLIC, SANTO DOMINGO" },
    { value: "GYQ", name: "ECUADOR, GUAYAQUIL" },
    { value: "QTO", name: "ECUADOR, QUITO" },
    { value: "CRO", name: "EGYPT, CAIRO" },
    { value: "SNS", name: "EL SALVADOR, SAN SALVADOR" },
    { value: "LND", name: "ENGLAND, LONDON" },
    { value: "MBO", name: "EQUATORIAL GUINEA, MALABO" },
    { value: "ASM", name: "ERITREA, ASMARA" },
    { value: "TAL", name: "ESTONIA, TALLINN" },
    { value: "MBA", name: "ESWATINI, MBABANE" },
    { value: "ADD", name: "ETHIOPIA, ADDIS ABABA" },
    { value: "SUV", name: "FIJI, SUVA" },
    { value: "HLS", name: "FINLAND, HELSINKI" },
    { value: "PRS", name: "FRANCE, PARIS" },
    { value: "LIB", name: "GABON, LIBREVILLE" },
    { value: "BAN", name: "GAMBIA, BANJUL" },
    { value: "TBL", name: "GEORGIA, TBILISI" },
    { value: "BRL", name: "GERMANY, BERLIN" },
    { value: "FRN", name: "GERMANY, FRANKFURT" },
    { value: "MUN", name: "GERMANY, MUNICH" },
    { value: "ACC", name: "GHANA, ACCRA" },
    { value: "ATH", name: "GREECE, ATHENS" },
    { value: "GTM", name: "GUATEMALA, GUATEMALA CITY" },
    { value: "CRY", name: "GUINEA, CONAKRY" },
    { value: "GEO", name: "GUYANA, GEORGETOWN" },
    { value: "PTP", name: "HAITI, PORT-AU-PRINCE" },
    { value: "TGG", name: "HONDURAS, TEGUCIGALPA" },
    { value: "HNK", name: "HONG KONG" },
    { value: "BDP", name: "HUNGARY, BUDAPEST" },
    { value: "RKJ", name: "ICELAND, REYKJAVIK" },
    { value: "MDR", name: "INDIA, CHENNAI" },
    { value: "HYD", name: "INDIA, HYDERABAD" },
    { value: "CLC", name: "INDIA, KOLKATA" },
    { value: "BMB", name: "INDIA, MUMBAI" },
    { value: "NWD", name: "INDIA, NEW DELHI" },
    { value: "JAK", name: "INDONESIA, JAKARTA" },
    { value: "SRB", name: "INDONESIA, SURABAYA" },
    { value: "BGH", name: "IRAQ, BAGHDAD" },
    { value: "ERB", name: "IRAQ, ERBIL" },
    { value: "DBL", name: "IRELAND, DUBLIN" },
    { value: "TLV", name: "ISRAEL, TEL AVIV" },
    { value: "FLR", name: "ITALY, FLORENCE" },
    { value: "MLN", name: "ITALY, MILAN" },
    { value: "NPL", name: "ITALY, NAPLES" },
    { value: "RME", name: "ITALY, ROME" },
    { value: "KNG", name: "JAMAICA, KINGSTON" },
    { value: "NHA", name: "JAPAN, NAHA" },
    { value: "KBO", name: "JAPAN, OSAKA/FUKUOKA" },
    { value: "TKY", name: "JAPAN, TOKYO/SAPPORO" },
    { value: "JRS", name: "JERUSALEM" },
    { value: "AMM", name: "JORDAN, AMMAN" },
    { value: "ATA", name: "KAZAKHSTAN, ALMATY" },
    { value: "AST", name: "KAZAKHSTAN, ASTANA" },
    { value: "NRB", name: "KENYA, NAIROBI" },
    { value: "PRI", name: "KOSOVO, PRISTINA" },
    { value: "KWT", name: "KUWAIT, KUWAIT CITY" },
    { value: "BKK", name: "KYRGYZSTAN, BISHKEK" },
    { value: "VNT", name: "LAOS, VIENTIANE" },
    { value: "RGA", name: "LATVIA, RIGA" },
    { value: "BRT", name: "LEBANON, BEIRUT" },
    { value: "MAS", name: "LESOTHO, MASERU" },
    { value: "MRV", name: "LIBERIA, MONROVIA" },
    { value: "VIL", name: "LITHUANIA, VILNIUS" },
    { value: "LXM", name: "LUXEMBOURG, LUXEMBOURG" },
    { value: "ANT", name: "MADAGASCAR, ANTANANARIVO" },
    { value: "LIL", name: "MALAWI, LILONGWE" },
    { value: "KLL", name: "MALAYSIA, KUALA LUMPUR" },
    { value: "BAM", name: "MALI, BAMAKO" },
    { value: "VLL", name: "MALTA, VALLETTA" },
    { value: "MAJ", name: "MARSHALL ISLANDS, MAJURO" },
    { value: "NUK", name: "MAURITANIA, NOUAKCHOTT" },
    { value: "PTL", name: "MAURITIUS, PORT LOUIS" },
    { value: "CDJ", name: "MEXICO, CIUDAD JUAREZ" },
    { value: "GDL", name: "MEXICO, GUADALAJARA" },
    { value: "HER", name: "MEXICO, HERMOSILLO" },
    { value: "MTM", name: "MEXICO, MATAMOROS" },
    { value: "MER", name: "MEXICO, MERIDA" },
    { value: "MEX", name: "MEXICO, MEXICO CITY" },
    { value: "MTR", name: "MEXICO, MONTERREY" },
    { value: "NGL", name: "MEXICO, NOGALES" },
    { value: "NVL", name: "MEXICO, NUEVO LAREDO" },
    { value: "TJT", name: "MEXICO, TIJUANA" },
    { value: "KOL", name: "MICRONESIA, KOLONIA" },
    { value: "CHS", name: "MOLDOVA, CHISINAU" },
    { value: "ULN", name: "MONGOLIA, ULAANBAATAR" },
    { value: "POD", name: "MONTENEGRO, PODGORICA" },
    { value: "CSB", name: "MOROCCO, CASABLANCA" },
    { value: "MAP", name: "MOZAMBIQUE, MAPUTO" },
    { value: "WHK", name: "NAMIBIA, WINDHOEK" },
    { value: "KDU", name: "NEPAL, KATHMANDU" },
    { value: "AMS", name: "NETHERLANDS, AMSTERDAM" },
    { value: "ACK", name: "NEW ZEALAND, AUCKLAND" },
    { value: "MNG", name: "NICARAGUA, MANAGUA" },
    { value: "NMY", name: "NIGER, NIAMEY" },
    { value: "ABU", name: "NIGERIA, ABUJA" },
    { value: "LGS", name: "NIGERIA, LAGOS" },
    { value: "SKO", name: "NORTH MACEDONIA, SKOPJE" },
    { value: "BLF", name: "NORTHERN IRELAND, BELFAST" },
    { value: "OSL", name: "NORWAY, OSLO" },
    { value: "MST", name: "OMAN, MUSCAT" },
    { value: "ISL", name: "PAKISTAN, ISLAMABAD" },
    { value: "KRC", name: "PAKISTAN, KARACHI" },
    { value: "KOR", name: "PALAU, KOROR" },
    { value: "PNM", name: "PANAMA, PANAMA CITY" },
    { value: "PTM", name: "PAPUA NEW GUINEA, PORT MORESBY" },
    { value: "ASN", name: "PARAGUAY, ASUNCION" },
    { value: "LMA", name: "PERU, LIMA" },
    { value: "MNL", name: "PHILIPPINES, MANILA" },
    { value: "KRK", name: "POLAND, KRAKOW" },
    { value: "WRW", name: "POLAND, WARSAW" },
    { value: "LSB", name: "PORTUGAL, LISBON" },
    { value: "DOH", name: "QATAR, DOHA" },
    { value: "BCH", name: "ROMANIA, BUCHAREST" },
    { value: "MOS", name: "RUSSIA, MOSCOW" },
    { value: "YEK", name: "RUSSIA, YEKATERINBURG" },
    { value: "KGL", name: "RWANDA, KIGALI" },
    { value: "APA", name: "SAMOA, APIA" },
    { value: "DHR", name: "SAUDI ARABIA, DHAHRAN" },
    { value: "JDD", name: "SAUDI ARABIA, JEDDAH" },
    { value: "RID", name: "SAUDI ARABIA, RIYADH" },
    { value: "DKR", name: "SENEGAL, DAKAR" },
    { value: "BLG", name: "SERBIA, BELGRADE" },
    { value: "FTN", name: "SIERRA LEONE, FREETOWN" },
    { value: "SGP", name: "SINGAPORE, SINGAPORE" },
    { value: "BTS", name: "SLOVAKIA, BRATISLAVA" },
    { value: "LJU", name: "SLOVENIA, LJUBLJANA" },
    { value: "CPT", name: "SOUTH AFRICA, CAPE TOWN" },
    { value: "DRB", name: "SOUTH AFRICA, DURBAN" },
    { value: "JHN", name: "SOUTH AFRICA, JOHANNESBURG" },
    { value: "SEO", name: "SOUTH KOREA, SEOUL" },
    { value: "JBA", name: "SOUTH SUDAN, JUBA" },
    { value: "MDD", name: "SPAIN, MADRID" },
    { value: "CLM", name: "SRI LANKA, COLOMBO" },
    { value: "KHT", name: "SUDAN, KHARTOUM" },
    { value: "PRM", name: "SURINAME, PARAMARIBO" },
    { value: "STK", name: "SWEDEN, STOCKHOLM" },
    { value: "BEN", name: "SWITZERLAND, BERN" },
    { value: "TAI", name: "TAIWAN, TAIPEI" },
    { value: "DHB", name: "TAJIKISTAN, DUSHANBE" },
    { value: "DRS", name: "TANZANIA, DAR ES SALAAM" },
    { value: "BNK", name: "THAILAND, BANGKOK" },
    { value: "CHN", name: "THAILAND, CHIANG MAI" },
    { value: "DIL", name: "TIMOR LESTE, DILI" },
    { value: "LOM", name: "TOGO, LOME" },
    { value: "PTS", name: "TRINIDAD, PORT OF SPAIN" },
    { value: "TNS", name: "TUNISIA, TUNIS" },
    { value: "ANK", name: "TURKEY, ANKARA" },
    { value: "IST", name: "TURKEY, ISTANBUL" },
    { value: "AKD", name: "TURKMENISTAN, ASHGABAT" },
    { value: "KMP", name: "UGANDA, KAMPALA" },
    { value: "KEV", name: "UKRAINE, KYIV" },
    { value: "ABD", name: "UNITED ARAB EMIRATES, ABU DHABI" },
    { value: "DUB", name: "UNITED ARAB EMIRATES, DUBAI" },
    { value: "MTV", name: "URUGUAY, MONTEVIDEO" },
    { value: "THT", name: "UZBEKISTAN, TASHKENT" },
    { value: "HAN", name: "VIETNAM, HANOI" },
    { value: "HCM", name: "VIETNAM, HO CHI MINH CITY" },
    { value: "LUS", name: "ZAMBIA, LUSAKA" },
    { value: "HRE", name: "ZIMBABWE, HARARE" },


]

export const stateList: DropDownList[] = [
    { value: "AL", name: "ALABAMA" },
    { value: "AK", name: "ALASKA" },
    { value: "AS", name: "AMERICAN SAMOA" },
    { value: "AZ", name: "ARIZONA" },
    { value: "AR", name: "ARKANSAS" },
    { value: "CA", name: "CALIFORNIA" },
    { value: "CO", name: "COLORADO" },
    { value: "CT", name: "CONNECTICUT" },
    { value: "DE", name: "DELAWARE" },
    { value: "DC", name: "DISTRICT OF COLUMBIA" },
    { value: "FL", name: "FLORIDA" },
    { value: "GA", name: "GEORGIA" },
    { value: "GU", name: "GUAM" },
    { value: "HI", name: "HAWAII" },
    { value: "ID", name: "IDAHO" },
    { value: "IL", name: "ILLINOIS" },
    { value: "IN", name: "INDIANA" },
    { value: "IA", name: "IOWA" },
    { value: "KS", name: "KANSAS" },
    { value: "KY", name: "KENTUCKY" },
    { value: "LA", name: "LOUISIANA" },
    { value: "ME", name: "MAINE" },
    { value: "MD", name: "MARYLAND" },
    { value: "MA", name: "MASSACHUSETTS" },
    { value: "MI", name: "MICHIGAN" },
    { value: "MN", name: "MINNESOTA" },
    { value: "MS", name: "MISSISSIPPI" },
    { value: "MO", name: "MISSOURI" },
    { value: "MT", name: "MONTANA" },
    { value: "NE", name: "NEBRASKA" },
    { value: "NV", name: "NEVADA" },
    { value: "NH", name: "NEW HAMPSHIRE" },
    { value: "NJ", name: "NEW JERSEY" },
    { value: "NM", name: "NEW MEXICO" },
    { value: "NY", name: "NEW YORK" },
    { value: "NC", name: "NORTH CAROLINA" },
    { value: "ND", name: "NORTH DAKOTA" },
    { value: "MP", name: "NORTHERN MARIANA ISLANDS" },
    { value: "OH", name: "OHIO" },
    { value: "OK", name: "OKLAHOMA" },
    { value: "OR", name: "OREGON" },
    { value: "PA", name: "PENNSYLVANIA" },
    { value: "PR", name: "PUERTO RICO" },
    { value: "RI", name: "RHODE ISLAND" },
    { value: "SC", name: "SOUTH CAROLINA" },
    { value: "SD", name: "SOUTH DAKOTA" },
    { value: "TN", name: "TENNESSEE" },
    { value: "TX", name: "TEXAS" },
    { value: "UT", name: "UTAH" },
    { value: "VT", name: "VERMONT" },
    { value: "VI", name: "VIRGIN ISLANDS" },
    { value: "VA", name: "VIRGINIA" },
    { value: "WA", name: "WASHINGTON" },
    { value: "WV", name: "WEST VIRGINIA" },
    { value: "WI", name: "WISCONSIN" },
    { value: "WY", name: "WYOMING" }
]

export const otherNationalityCountryList: DropDownList[] = [
    { value: "AFGH", name: "AFGHANISTAN" },
    { value: "ALB", name: "ALBANIA" },
    { value: "ALGR", name: "ALGERIA" },
    { value: "ANDO", name: "ANDORRA" },
    { value: "ANGL", name: "ANGOLA" },
    { value: "ANGU", name: "ANGUILLA" },
    { value: "ANTI", name: "ANTIGUA AND BARBUDA" },
    { value: "ARG", name: "ARGENTINA" },
    { value: "ARM", name: "ARMENIA" },
    { value: "ASTL", name: "AUSTRALIA" },
    { value: "AUST", name: "AUSTRIA" },
    { value: "AZR", name: "AZERBAIJAN" },
    { value: "BAMA", name: "BAHAMAS" },
    { value: "BAHR", name: "BAHRAIN" },
    { value: "BANG", name: "BANGLADESH" },
    { value: "BRDO", name: "BARBADOS" },
    { value: "BYS", name: "BELARUS" },
    { value: "BELG", name: "BELGIUM" },
    { value: "BLZ", name: "BELIZE" },
    { value: "BENN", name: "BENIN" },
    { value: "BERM", name: "BERMUDA" },
    { value: "BHU", name: "BHUTAN" },
    { value: "BOL", name: "BOLIVIA" },
    { value: "BIH", name: "BOSNIA-HERZEGOVINA" },
    { value: "BOT", name: "BOTSWANA" },
    { value: "BRZL", name: "BRAZIL" },
    { value: "BRNI", name: "BRUNEI" },
    { value: "BULG", name: "BULGARIA" },
    { value: "BURK", name: "BURKINA FASO" },
    { value: "BURM", name: "BURMA" },
    { value: "BRND", name: "BURUNDI" },
    { value: "CBDA", name: "CAMBODIA" },
    { value: "CMRN", name: "CAMEROON" },
    { value: "CAN", name: "CANADA" },
    { value: "CAVI", name: "CABO VERDE" },
    { value: "CAYI", name: "CAYMAN ISLANDS" },
    { value: "CAFR", name: "CENTRAL AFRICAN REPUBLIC" },
    { value: "CHAD", name: "CHAD" },
    { value: "CHIL", name: "CHILE" },
    { value: "CHIN", name: "CHINA" },
    { value: "COL", name: "COLOMBIA" },
    { value: "COMO", name: "COMOROS" },
    { value: "COD", name: "CONGO, DEMOCRATIC REPUBLIC OF THE" },
    { value: "CONB", name: "CONGO, REPUBLIC OF THE" },
    { value: "CSTR", name: "COSTA RICA" },
    { value: "IVCO", name: "COTE D`IVOIRE" },
    { value: "HRV", name: "CROATIA" },
    { value: "CUBA", name: "CUBA" },
    { value: "CYPR", name: "CYPRUS" },
    { value: "CZEC", name: "CZECH REPUBLIC" },
    { value: "DEN", name: "DENMARK" },
    { value: "DJI", name: "DJIBOUTI" },
    { value: "DOMN", name: "DOMINICA" },
    { value: "DOMR", name: "DOMINICAN REPUBLIC" },
    { value: "ECUA", name: "ECUADOR" },
    { value: "EGYP", name: "EGYPT" },
    { value: "ELSL", name: "EL SALVADOR" },
    { value: "EGN", name: "EQUATORIAL GUINEA" },
    { value: "ERI", name: "ERITREA" },
    { value: "EST", name: "ESTONIA" },
    { value: "SZLD", name: "ESWATINI" },
    { value: "ETH", name: "ETHIOPIA" },
    { value: "FIJI", name: "FIJI" },
    { value: "FIN", name: "FINLAND" },
    { value: "FRAN", name: "FRANCE" },
    { value: "GABN", name: "GABON" },
    { value: "GAM", name: "GAMBIA, THE" },
    { value: "GEO", name: "GEORGIA" },
    { value: "GER", name: "GERMANY" },
    { value: "GHAN", name: "GHANA" },
    { value: "GIB", name: "GIBRALTAR" },
    { value: "GRC", name: "GREECE" },
    { value: "GREN", name: "GRENADA" },
    { value: "GUAT", name: "GUATEMALA" },
    { value: "GNEA", name: "GUINEA" },
    { value: "GUIB", name: "GUINEA - BISSAU" },
    { value: "GUY", name: "GUYANA" },
    { value: "HAT", name: "HAITI" },
    { value: "VAT", name: "HOLY SEE (VATICAN CITY)" },
    { value: "HOND", name: "HONDURAS" },
    { value: "HOKO", name: "HONG KONG BNO" },
    { value: "HNK", name: "HONG KONG SAR" },
    { value: "HUNG", name: "HUNGARY" },
    { value: "ICLD", name: "ICELAND" },
    { value: "IND", name: "INDIA" },
    { value: "IDSA", name: "INDONESIA" },
    { value: "IRAN", name: "IRAN" },
    { value: "IRAQ", name: "IRAQ" },
    { value: "IRE", name: "IRELAND" },
    { value: "ISRL", name: "ISRAEL" },
    { value: "ITLY", name: "ITALY" },
    { value: "JAM", name: "JAMAICA" },
    { value: "JPN", name: "JAPAN" },
    { value: "JORD", name: "JORDAN" },
    { value: "KAZ", name: "KAZAKHSTAN" },
    { value: "KENY", name: "KENYA" },
    { value: "KIRI", name: "KIRIBATI" },
    { value: "PRK", name: "KOREA, DEMOCRATIC REPUBLIC OF (NORTH)" },
    { value: "KOR", name: "KOREA, REPUBLIC OF (SOUTH)" },
    { value: "KSV", name: "KOSOVO" },
    { value: "KUWT", name: "KUWAIT" },
    { value: "KGZ", name: "KYRGYZSTAN" },
    { value: "LAOS", name: "LAOS" },
    { value: "LATV", name: "LATVIA" },
    { value: "LEBN", name: "LEBANON" },
    { value: "LES", name: "LESOTHO" },
    { value: "LIBR", name: "LIBERIA" },
    { value: "LBYA", name: "LIBYA" },
    { value: "LCHT", name: "LIECHTENSTEIN" },
    { value: "LITH", name: "LITHUANIA" },
    { value: "LXM", name: "LUXEMBOURG" },
    { value: "MAC", name: "MACAU" },
    { value: "MKD", name: "MACEDONIA, NORTH" },
    { value: "MADG", name: "MADAGASCAR" },
    { value: "MALW", name: "MALAWI" },
    { value: "MLAS", name: "MALAYSIA" },
    { value: "MLDV", name: "MALDIVES" },
    { value: "MALI", name: "MALI" },
    { value: "MLTA", name: "MALTA" },
    { value: "RMI", name: "MARSHALL ISLANDS" },
    { value: "MAUR", name: "MAURITANIA" },
    { value: "MRTS", name: "MAURITIUS" },
    { value: "MEX", name: "MEXICO" },
    { value: "FSM", name: "MICRONESIA" },
    { value: "MLD", name: "MOLDOVA" },
    { value: "MON", name: "MONACO" },
    { value: "MONG", name: "MONGOLIA" },
    { value: "MTG", name: "MONTENEGRO" },
    { value: "MONT", name: "MONTSERRAT" },
    { value: "MORO", name: "MOROCCO" },
    { value: "MOZ", name: "MOZAMBIQUE" },
    { value: "NAMB", name: "NAMIBIA" },
    { value: "NAU", name: "NAURU" },
    { value: "NEP", name: "NEPAL" },
    { value: "NETH", name: "NETHERLANDS" },
    { value: "NZLD", name: "NEW ZEALAND" },
    { value: "NIC", name: "NICARAGUA" },
    { value: "NIR", name: "NIGER" },
    { value: "NRA", name: "NIGERIA" },
    { value: "NORW", name: "NORWAY" },
    { value: "OMAN", name: "OMAN" },
    { value: "PKST", name: "PAKISTAN" },
    { value: "PALA", name: "PALAU" },
    { value: "PAL", name: "PALESTINIAN AUTHORITY" },
    { value: "PAN", name: "PANAMA" },
    { value: "PNG", name: "PAPUA NEW GUINEA" },
    { value: "PARA", name: "PARAGUAY" },
    { value: "PERU", name: "PERU" },
    { value: "PHIL", name: "PHILIPPINES" },
    { value: "PITC", name: "PITCAIRN ISLANDS" },
    { value: "POL", name: "POLAND" },
    { value: "PORT", name: "PORTUGAL" },
    { value: "QTAR", name: "QATAR" },
    { value: "ROM", name: "ROMANIA" },
    { value: "RUS", name: "RUSSIA" },
    { value: "RWND", name: "RWANDA" },
    { value: "WSAM", name: "SAMOA" },
    { value: "SMAR", name: "SAN MARINO" },
    { value: "STPR", name: "SAO TOME AND PRINCIPE" },
    { value: "SARB", name: "SAUDI ARABIA" },
    { value: "SENG", name: "SENEGAL" },
    { value: "SBA", name: "SERBIA" },
    { value: "SEYC", name: "SEYCHELLES" },
    { value: "SLEO", name: "SIERRA LEONE" },
    { value: "SING", name: "SINGAPORE" },
    { value: "SVK", name: "SLOVAKIA" },
    { value: "SVN", name: "SLOVENIA" },
    { value: "SLMN", name: "SOLOMON ISLANDS" },
    { value: "SOMA", name: "SOMALIA" },
    { value: "SAFR", name: "SOUTH AFRICA" },
    { value: "SSDN", name: "SOUTH SUDAN" },
    { value: "SPN", name: "SPAIN" },
    { value: "SRL", name: "SRI LANKA" },
    { value: "SHEL", name: "ST. HELENA" },
    { value: "STCN", name: "ST. KITTS AND NEVIS" },
    { value: "SLCA", name: "ST. LUCIA" },
    { value: "STVN", name: "ST. VINCENT AND THE GRENADINES" },
    { value: "SUDA", name: "SUDAN" },
    { value: "SURM", name: "SURINAME" },
    { value: "SWDN", name: "SWEDEN" },
    { value: "SWTZ", name: "SWITZERLAND" },
    { value: "SYR", name: "SYRIA" },
    { value: "TWAN", name: "TAIWAN" },
    { value: "TJK", name: "TAJIKISTAN" },
    { value: "TAZN", name: "TANZANIA" },
    { value: "THAI", name: "THAILAND" },
    { value: "TMOR", name: "TIMOR-LESTE" },
    { value: "TOGO", name: "TOGO" },
    { value: "TONG", name: "TONGA" },
    { value: "TRIN", name: "TRINIDAD AND TOBAGO" },
    { value: "TNSA", name: "TUNISIA" },
    { value: "TRKY", name: "TURKEY" },
    { value: "TKM", name: "TURKMENISTAN" },
    { value: "TCIS", name: "TURKS AND CAICOS ISLANDS" },
    { value: "TUV", name: "TUVALU" },
    { value: "UGAN", name: "UGANDA" },
    { value: "UKR", name: "UKRAINE" },
    { value: "UAE", name: "UNITED ARAB EMIRATES" },
    { value: "GRBR", name: "UNITED KINGDOM" },
    { value: "USA", name: "UNITED STATES OF AMERICA" },
    { value: "URU", name: "URUGUAY" },
    { value: "UZB", name: "UZBEKISTAN" },
    { value: "VANU", name: "VANUATU" },
    { value: "VENZ", name: "VENEZUELA" },
    { value: "VTNM", name: "VIETNAM" },
    { value: "BRVI", name: "VIRGIN ISLANDS, BRITISH" },
    { value: "WAFT", name: "WALLIS AND FUTUNA ISLANDS" },
    { value: "SSAH", name: "WESTERN SAHARA" },
    { value: "YEM", name: "YEMEN" },
    { value: "ZAMB", name: "ZAMBIA" },
    { value: "ZIMB", name: "ZIMBABWE" }
]

export const payerCountryList: DropDownList[] = [
    { value: "AFGH", name: "AFGHANISTAN" },
    { value: "ALB", name: "ALBANIA" },
    { value: "ALGR", name: "ALGERIA" },
    { value: "ASMO", name: "AMERICAN SAMOA" },
    { value: "ANDO", name: "ANDORRA" },
    { value: "ANGL", name: "ANGOLA" },
    { value: "ANGU", name: "ANGUILLA" },
    { value: "ANTI", name: "ANTIGUA AND BARBUDA" },
    { value: "ARG", name: "ARGENTINA" },
    { value: "ARM", name: "ARMENIA" },
    { value: "ARB", name: "ARUBA" },
    { value: "ASTL", name: "AUSTRALIA" },
    { value: "AUST", name: "AUSTRIA" },
    { value: "AZR", name: "AZERBAIJAN" },
    { value: "BAMA", name: "BAHAMAS" },
    { value: "BAHR", name: "BAHRAIN" },
    { value: "BANG", name: "BANGLADESH" },
    { value: "BRDO", name: "BARBADOS" },
    { value: "BYS", name: "BELARUS" },
    { value: "BELG", name: "BELGIUM" },
    { value: "BLZ", name: "BELIZE" },
    { value: "BENN", name: "BENIN" },
    { value: "BERM", name: "BERMUDA" },
    { value: "BHU", name: "BHUTAN" },
    { value: "BOL", name: "BOLIVIA" },
    { value: "BON", name: "BONAIRE" },
    { value: "BIH", name: "BOSNIA-HERZEGOVINA" },
    { value: "BOT", name: "BOTSWANA" },
    { value: "BRZL", name: "BRAZIL" },
    { value: "IOT", name: "BRITISH INDIAN OCEAN TERRITORY" },
    { value: "BRNI", name: "BRUNEI" },
    { value: "BULG", name: "BULGARIA" },
    { value: "BURK", name: "BURKINA FASO" },
    { value: "BURM", name: "BURMA" },
    { value: "BRND", name: "BURUNDI" },
    { value: "CBDA", name: "CAMBODIA" },
    { value: "CMRN", name: "CAMEROON" },
    { value: "CAN", name: "CANADA" },
    { value: "CAVI", name: "CABO VERDE" },
    { value: "CAYI", name: "CAYMAN ISLANDS" },
    { value: "CAFR", name: "CENTRAL AFRICAN REPUBLIC" },
    { value: "CHAD", name: "CHAD" },
    { value: "CHIL", name: "CHILE" },
    { value: "CHIN", name: "CHINA" },
    { value: "CHRI", name: "CHRISTMAS ISLAND" },
    { value: "COCI", name: "COCOS KEELING ISLANDS" },
    { value: "COL", name: "COLOMBIA" },
    { value: "COMO", name: "COMOROS" },
    { value: "COD", name: "CONGO, DEMOCRATIC REPUBLIC OF THE" },
    { value: "CONB", name: "CONGO, REPUBLIC OF THE" },
    { value: "CKIS", name: "COOK ISLANDS" },
    { value: "CSTR", name: "COSTA RICA" },
    { value: "IVCO", name: "COTE D`IVOIRE" },
    { value: "HRV", name: "CROATIA" },
    { value: "CUBA", name: "CUBA" },
    { value: "CUR", name: "CURACAO" },
    { value: "CYPR", name: "CYPRUS" },
    { value: "CZEC", name: "CZECH REPUBLIC" },
    { value: "DEN", name: "DENMARK" },
    { value: "DJI", name: "DJIBOUTI" },
    { value: "DOMN", name: "DOMINICA" },
    { value: "DOMR", name: "DOMINICAN REPUBLIC" },
    { value: "ECUA", name: "ECUADOR" },
    { value: "EGYP", name: "EGYPT" },
    { value: "ELSL", name: "EL SALVADOR" },
    { value: "EGN", name: "EQUATORIAL GUINEA" },
    { value: "ERI", name: "ERITREA" },
    { value: "EST", name: "ESTONIA" },
    { value: "SZLD", name: "ESWATINI" },
    { value: "ETH", name: "ETHIOPIA" },
    { value: "FKLI", name: "FALKLAND ISLANDS" },
    { value: "FRO", name: "FAROE ISLANDS" },
    { value: "FIJI", name: "FIJI" },
    { value: "FIN", name: "FINLAND" },
    { value: "FRAN", name: "FRANCE" },
    { value: "FRGN", name: "FRENCH GUIANA" },
    { value: "FPOL", name: "FRENCH POLYNESIA" },
    { value: "FSAT", name: "FRENCH SOUTHERN AND ANTARCTIC TERRITORIES" },
    { value: "GABN", name: "GABON" },
    { value: "GAM", name: "GAMBIA, THE" },
    { value: "XGZ", name: "GAZA STRIP" },
    { value: "GEO", name: "GEORGIA" },
    { value: "GER", name: "GERMANY" },
    { value: "GHAN", name: "GHANA" },
    { value: "GIB", name: "GIBRALTAR" },
    { value: "GRC", name: "GREECE" },
    { value: "GRLD", name: "GREENLAND" },
    { value: "GREN", name: "GRENADA" },
    { value: "GUAD", name: "GUADELOUPE" },
    { value: "GUAM", name: "GUAM" },
    { value: "GUAT", name: "GUATEMALA" },
    { value: "GNEA", name: "GUINEA" },
    { value: "GUIB", name: "GUINEA - BISSAU" },
    { value: "GUY", name: "GUYANA" },
    { value: "HAT", name: "HAITI" },
    { value: "HMD", name: "HEARD AND MCDONALD ISLANDS" },
    { value: "VAT", name: "HOLY SEE (VATICAN CITY)" },
    { value: "HOND", name: "HONDURAS" },
    { value: "HNK", name: "HONG KONG" },
    { value: "XHI", name: "HOWLAND ISLAND" },
    { value: "HUNG", name: "HUNGARY" },
    { value: "ICLD", name: "ICELAND" },
    { value: "IND", name: "INDIA" },
    { value: "IDSA", name: "INDONESIA" },
    { value: "IRAN", name: "IRAN" },
    { value: "IRAQ", name: "IRAQ" },
    { value: "IRE", name: "IRELAND" },
    { value: "ISRL", name: "ISRAEL" },
    { value: "ITLY", name: "ITALY" },
    { value: "JAM", name: "JAMAICA" },
    { value: "JPN", name: "JAPAN" },
    { value: "JRSM", name: "JERUSALEM" },
    { value: "JORD", name: "JORDAN" },
    { value: "KAZ", name: "KAZAKHSTAN" },
    { value: "KENY", name: "KENYA" },
    { value: "KIRI", name: "KIRIBATI" },
    { value: "PRK", name: "KOREA, DEMOCRATIC REPUBLIC OF (NORTH)" },
    { value: "KOR", name: "KOREA, REPUBLIC OF (SOUTH)" },
    { value: "KSV", name: "KOSOVO" },
    { value: "KUWT", name: "KUWAIT" },
    { value: "KGZ", name: "KYRGYZSTAN" },
    { value: "LAOS", name: "LAOS" },
    { value: "LATV", name: "LATVIA" },
    { value: "LEBN", name: "LEBANON" },
    { value: "LES", name: "LESOTHO" },
    { value: "LIBR", name: "LIBERIA" },
    { value: "LBYA", name: "LIBYA" },
    { value: "LCHT", name: "LIECHTENSTEIN" },
    { value: "LITH", name: "LITHUANIA" },
    { value: "LXM", name: "LUXEMBOURG" },
    { value: "MAC", name: "MACAU" },
    { value: "MKD", name: "MACEDONIA, NORTH" },
    { value: "MADG", name: "MADAGASCAR" },
    { value: "MALW", name: "MALAWI" },
    { value: "MLAS", name: "MALAYSIA" },
    { value: "MLDI", name: "MALDEN ISLAND" },
    { value: "MLDV", name: "MALDIVES" },
    { value: "MALI", name: "MALI" },
    { value: "MLTA", name: "MALTA" },
    { value: "RMI", name: "MARSHALL ISLANDS" },
    { value: "MART", name: "MARTINIQUE" },
    { value: "MAUR", name: "MAURITANIA" },
    { value: "MRTS", name: "MAURITIUS" },
    { value: "MYT", name: "MAYOTTE" },
    { value: "MEX", name: "MEXICO" },
    { value: "FSM", name: "MICRONESIA" },
    { value: "MDWI", name: "MIDWAY ISLANDS" },
    { value: "MLD", name: "MOLDOVA" },
    { value: "MON", name: "MONACO" },
    { value: "MONG", name: "MONGOLIA" },
    { value: "MTG", name: "MONTENEGRO" },
    { value: "MONT", name: "MONTSERRAT" },
    { value: "MORO", name: "MOROCCO" },
    { value: "MOZ", name: "MOZAMBIQUE" },
    { value: "NAMB", name: "NAMIBIA" },
    { value: "NAU", name: "NAURU" },
    { value: "NEP", name: "NEPAL" },
    { value: "NETH", name: "NETHERLANDS" },
    { value: "NCAL", name: "NEW CALEDONIA" },
    { value: "NZLD", name: "NEW ZEALAND" },
    { value: "NIC", name: "NICARAGUA" },
    { value: "NIR", name: "NIGER" },
    { value: "NRA", name: "NIGERIA" },
    { value: "NIUE", name: "NIUE" },
    { value: "NFK", name: "NORFOLK ISLAND" },
    { value: "MNP", name: "NORTH MARIANA ISLANDS" },
    { value: "NIRE", name: "NORTHERN IRELAND" },
    { value: "NORW", name: "NORWAY" },
    { value: "OMAN", name: "OMAN" },
    { value: "PKST", name: "PAKISTAN" },
    { value: "PALA", name: "PALAU" },
    { value: "PLMR", name: "PALMYRA ATOLL" },
    { value: "PAN", name: "PANAMA" },
    { value: "PNG", name: "PAPUA NEW GUINEA" },
    { value: "PARA", name: "PARAGUAY" },
    { value: "PERU", name: "PERU" },
    { value: "PHIL", name: "PHILIPPINES" },
    { value: "PITC", name: "PITCAIRN ISLANDS" },
    { value: "POL", name: "POLAND" },
    { value: "PORT", name: "PORTUGAL" },
    { value: "PR", name: "PUERTO RICO" },
    { value: "QTAR", name: "QATAR" },
    { value: "REUN", name: "REUNION" },
    { value: "ROM", name: "ROMANIA" },
    { value: "RUS", name: "RUSSIA" },
    { value: "RWND", name: "RWANDA" },
    { value: "SABA", name: "SABA ISLAND" },
    { value: "MAF", name: "SAINT MARTIN" },
    { value: "WSAM", name: "SAMOA" },
    { value: "SMAR", name: "SAN MARINO" },
    { value: "STPR", name: "SAO TOME AND PRINCIPE" },
    { value: "SARB", name: "SAUDI ARABIA" },
    { value: "SENG", name: "SENEGAL" },
    { value: "SBA", name: "SERBIA" },
    { value: "SEYC", name: "SEYCHELLES" },
    { value: "SLEO", name: "SIERRA LEONE" },
    { value: "SING", name: "SINGAPORE" },
    { value: "STM", name: "SINT MAARTEN" },
    { value: "SVK", name: "SLOVAKIA" },
    { value: "SVN", name: "SLOVENIA" },
    { value: "SLMN", name: "SOLOMON ISLANDS" },
    { value: "SOMA", name: "SOMALIA" },
    { value: "SAFR", name: "SOUTH AFRICA" },
    { value: "SGS", name: "SOUTH GEORGIA AND THE SOUTH SANDWICH ISLAND" },
    { value: "SSDN", name: "SOUTH SUDAN" },
    { value: "SPN", name: "SPAIN" },
    { value: "SRL", name: "SRI LANKA" },
    { value: "STEU", name: "ST. EUSTATIUS" },
    { value: "SHEL", name: "ST. HELENA" },
    { value: "STCN", name: "ST. KITTS AND NEVIS" },
    { value: "SLCA", name: "ST. LUCIA" },
    { value: "SPMI", name: "ST. PIERRE AND MIQUELON" },
    { value: "STVN", name: "ST. VINCENT AND THE GRENADINES" },
    { value: "SUDA", name: "SUDAN" },
    { value: "SURM", name: "SURINAME" },
    { value: "SJM", name: "SVALBARD" },
    { value: "SWDN", name: "SWEDEN" },
    { value: "SWTZ", name: "SWITZERLAND" },
    { value: "SYR", name: "SYRIA" },
    { value: "TWAN", name: "TAIWAN" },
    { value: "TJK", name: "TAJIKISTAN" },
    { value: "TAZN", name: "TANZANIA" },
    { value: "THAI", name: "THAILAND" },
    { value: "TMOR", name: "TIMOR-LESTE" },
    { value: "TOGO", name: "TOGO" },
    { value: "TKL", name: "TOKELAU" },
    { value: "TONG", name: "TONGA" },
    { value: "TRIN", name: "TRINIDAD AND TOBAGO" },
    { value: "TNSA", name: "TUNISIA" },
    { value: "TRKY", name: "TURKEY" },
    { value: "TKM", name: "TURKMENISTAN" },
    { value: "TCIS", name: "TURKS AND CAICOS ISLANDS" },
    { value: "TUV", name: "TUVALU" },
    { value: "UGAN", name: "UGANDA" },
    { value: "UKR", name: "UKRAINE" },
    { value: "UAE", name: "UNITED ARAB EMIRATES" },
    { value: "GRBR", name: "UNITED KINGDOM" },
    { value: "USA", name: "UNITED STATES OF AMERICA" },
    { value: "URU", name: "URUGUAY" },
    { value: "UZB", name: "UZBEKISTAN" },
    { value: "VANU", name: "VANUATU" },
    { value: "VENZ", name: "VENEZUELA" },
    { value: "VTNM", name: "VIETNAM" },
    { value: "VI", name: "VIRGIN ISLANDS (U.S.)" },
    { value: "BRVI", name: "VIRGIN ISLANDS, BRITISH" },
    { value: "WKI", name: "WAKE ISLAND" },
    { value: "WAFT", name: "WALLIS AND FUTUNA ISLANDS" },
    { value: "XWB", name: "WEST BANK" },
    { value: "SSAH", name: "WESTERN SAHARA" },
    { value: "YEM", name: "YEMEN" },
    { value: "ZAMB", name: "ZAMBIA" },
    { value: "ZIMB", name: "ZIMBABWE" },
]

export const socialMediaList: DropDownList[] = [
    { value: "ASKF", name: "ASK.FM" },
    { value: "DUBN", name: "DOUBAN" },
    { value: "FCBK", name: "FACEBOOK" },
    { value: "FLKR", name: "FLICKR" },
    { value: "GOGL", name: "GOOGLE+" },
    { value: "INST", name: "INSTAGRAM" },
    { value: "LINK", name: "LINKEDIN" },
    { value: "MYSP", name: "MYSPACE" },
    { value: "PTST", name: "PINTEREST" },
    { value: "QZNE", name: "QZONE (QQ)" },
    { value: "RDDT", name: "REDDIT" },
    { value: "SWBO", name: "SINA WEIBO" },
    { value: "TWBO", name: "TENCENT WEIBO" },
    { value: "TUMB", name: "TUMBLR" },
    { value: "TWIT", name: "TWITTER" },
    { value: "TWOO", name: "TWOO" },
    { value: "VINE", name: "VINE" },
    { value: "VKON", name: "VKONTAKTE (VK)" },
    { value: "YUKU", name: "YOUKU" },
    { value: "YTUB", name: "YOUTUBE" },
    { value: "NONE", name: "NONE" },
]